title: Vivek Das PhD, MSc
logo: /assets/newprofilepic.png
description: Lead Data Scientist @ Novo Nordisk A/S | Translational Omics and Computational Biology for Clinical-Decision Making | Applied Data Science & ML | Strategy, Innovation & Cross-Functional Leadership
show_downloads: true
theme: jekyll-theme-minimal
url: "https://vd4mmind.github.io"
baseurl: "/vivekdas.github.io"
